### ISSUE TITLE
One SQL query for calculating tags

### ISSUE THREAD

**Issue by galetahub** [zakrevitz/Rails_blog#1]
А давай зробимо ось цей код одним запитом в БД
https://github.com/zakrevitz/Rails_blog/blob/master/app/controllers/welcome_controller.rb#L7

**Comment by zakrevitz** [comment]
Зроблено.

**Comment by galetahub** [comment]
https://github.com/zakrevitz/Rails_blog/blob/master/app/controllers/welcome_controller.rb#L8 - так не можна робити адже ми завантажуємо в пам'ять всі записи із цієї таблички, що критично коли багато записів в табличці. 

Спробуй порахувати кількість тегів за допомогою SQL запиту
